require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  EnabledByDefault: true
  TargetRubyVersion: 3.2.2
  SuggestExtensions: false

Bundler/GemComment:
  Enabled: false

RuboCopBundler/GemVersion:
  Enabled: false


Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
  Max: 30

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 10

Naming/AccessorMethodName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false
