require:
  - standard
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

# Use the defaults from https://github.com/testdouble/standard
inherit_gem:
  standard: config/ruby-3.2.yml

inherit_from:
  - .rubocop_local.yml

AllCops:
  EnabledByDefault: true
  TargetRubyVersion: 3.2.2
  SuggestExtensions: false
  Exclude:
    - tmp/**/*
    - vendor/**/*
    - Brewfile
    - db/schema.rb
    - bin/**/*
